eureka:
  instance:
    hostname: eureka-server
    preferIpAddress: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  config:
    override.system-properties: false