spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order
    username: ahmad
    password: ahmad
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.type.mapping: orderConfirmation:com.example.ahmad.OrderService.Kafka.OrderConfirmation

application:
  config:
    customer-url: http://customer-service:8090/customers
    product-url: http://product-service:8050/products

server:
  port: 8070
