spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/payment
    username: ahmad
    password: ahmad
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.type.mapping: paymentConfirmation:com.ahmad.payment_service.Kafka.PaymentConfirmation

server:
  port: 8020