services:
  postgres:
    container_name: ms_pg_sql
    image: postgres:16.1
    environment:
      POSTGRES_USER: ahmad
      POSTGRES_PASSWORD: ahmad
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - microservices-net

  mongo:
    image: mongo:6.0
    container_name: ms_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ahmad
      MONGO_INITDB_ROOT_PASSWORD: ahmad
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - microservices-net
    command: [--auth]

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express:1-20
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ahmad
      ME_CONFIG_MONGODB_ADMINPASSWORD: ahmad
      ME_CONFIG_MONGODB_SERVER: ms_mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    depends_on:
      - mongo
  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP server
    networks:
      - microservices-net

  zookeeper:
    container_name: ms_zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - microservices-net

  kafka:
    container_name: ms_kafka
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ms_kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - microservices-net

  config-server:
    build: ./services/config-server
    container_name: config_server
    ports:
      - "8888:8888"
    networks:
      - microservices-net
    depends_on:
      - postgres

  eureka-server:
    build: ./services/Eureka-server
    container_name: eureka_server
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    depends_on:
      - config-server

#  customer-service:
#    build: ./services/customer-service
#    container_name: ms_customer
#    ports:
#      - "8090:8090"
#    networks:
#      - microservices-net
#    depends_on:
#      - config-server
#      - eureka-service
#      - postgres

#  product-service:
#    build: ./services/product-service
#    container_name: ms_product
#    ports:
#      - "8050:8050"
#    networks:
#      - microservices-net
#    depends_on:
#      - config-server
#      - eureka-service
#      - postgres
#
#  order-service:
#    build: ./services/order-service
#    container_name: ms_order
#    ports:
#      - "8070:8070"
#    networks:
#      - microservices-net
#    depends_on:
#      - config-server
#      - eureka-service
#      - postgres
#      - kafka

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: