version: '3.8'
services:
  postgres:
    container_name: ms_pg_sql
    image: postgres:16.1
    environment:
      POSTGRES_USER: ahmad
      POSTGRES_PASSWORD: ahmad
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - microservices-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: ms_pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - microservices-net
    depends_on:
      - postgres

  mongo:
    image: mongo:6.0
    container_name: ms_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ahmad
      MONGO_INITDB_ROOT_PASSWORD: ahmad
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - microservices-net
    command: [--auth]

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express:1-20
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ahmad
      ME_CONFIG_MONGODB_ADMINPASSWORD: ahmad
      ME_CONFIG_MONGODB_SERVER: ms_mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    depends_on:
      - mongo
  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP server
    networks:
      - microservices-net

  zookeeper:
    container_name: ms_zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - microservices-net

  kafka:
    container_name: ms_kafka
    image: confluentinc/cp-kafka:7.4.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: