spring:
  config:
    import: optional:configserver:http://config-server:8888  # Docker service name
  application:
    name: notification-service
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        max-attempts: 10